name: stateless_textfield
description: A Stateless TextField having an initialValue parameter.
version: 0.1.0
repository: https://github.com/Urotea/stateless_textfield

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
